apiVersion: batch/v1
kind: CronJob
metadata:
  name: add-todo
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: add-todo
            image: TODO_JOB
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "10m"
                memory: "5Mi"
              limits:
                cpu: "50m"
                memory: "44Mi"
            env:
            - name: BACKEND_URL
              value: "http://todo-backend-svc:3000"
          restartPolicy: OnFailure
