apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
      - name: broadcaster
        image: BROADCASTER
        imagePullPolicy: Always
        env:
          - name: NATS_URL
            value: nats://my-nats:4222
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegram-bot
                key: token
          - name: TELEGRAM_CHAT_ID
            valueFrom:
              secretKeyRef:
                name: telegram-bot
                key: chat_id