apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: placeholder
resources:
  - manifests/app-deployment.yaml
  - manifests/backend-deployment.yaml
  - manifests/add-todo-cronjob.yaml
  - manifests/httproute.yaml
  - manifests/gateway.yaml
  - manifests/backend-service.yaml
  - manifests/app-service.yaml
  - manifests/backend-configmap.yaml
  - manifests/postgres-service.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/pv/persistentvolumeclaim.yaml
  - manifests/pv/persistentvolume.yaml
  - manifests/broadcaster-deployment.yaml
  
configMapGenerator:
  - name: todo-app-config
    literals:
      - BACKEND_URL=http://localhost:8081
      - PORT=3000
      - CACHE_DIR=/app/cache