apiVersion: batch/v1
kind: CronJob
metadata:
  name: add-todo
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: add-todo
            image: TODO_JOB
            imagePullPolicy: Always
            env:
            - name: BACKEND_URL
              value: "http://todo-backend-svc:3000"
          restartPolicy: OnFailure
