apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: the-project-volume
          persistentVolumeClaim:
            claimName: the-project-claim
      containers:
        - name: todo-app
          image: TODO_APP
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: todo-app-config
          volumeMounts:
            - name: the-project-volume
              mountPath: /app/cache