apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-backup-cronjob
  namespace: project
spec:
  schedule: "0 2 * * *"   
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: google/cloud-sdk:slim
            resources:
              requests:
                cpu: "10m"
                memory: "30Mi"
              limits:
                cpu: "100m"
                memory: "64Mi"
            env:
            - name: PGPASSWORD
              value: projectpassword
            volumeMounts:
            - name: gcs-key
              mountPath: /secrets
              readOnly: true
            command:
            - /bin/bash
            - -c
            - |
              apt-get update
              apt-get install -y wget gnupg2 lsb-release
              echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
              wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
              apt-get update
              apt-get install -y postgresql-client-17
              export GOOGLE_APPLICATION_CREDENTIALS=/secrets/dwk-gke-463515-3552a7781b71.json
              export BACKUP_FILE="/tmp/backup-$(date +\%F).sql"
              pg_dump -h project-postgres-svc -U projectuser -d projectdb -f $BACKUP_FILE
              gsutil auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
              gsutil cp $BACKUP_FILE gs://laurijuhani-project-backup-bucket/
          restartPolicy: OnFailure
          volumes:
          - name: gcs-key
            secret:
              secretName: gcs-backup-sa
