apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: TODO_BACKEND
        imagePullPolicy: Never
        env:
          - name: NATS_URL
            value: nats://my-nats.project.svc.cluster.local:4222
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
          limits:
            cpu: "150m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: backend-config
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10