apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec: 
  type: NodePort
  selector: 
    app: todo-app
  ports:
    - name: htto
      nodePort: 30080
      protocol: TCP
      port: 3000
      targetPort: 3000