apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-claim
  namespace: exercises
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
