apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ./../../base
patches:
- path: broadcaster-deployment.yaml

namePrefix: staging-

images:
- name: BROADCASTER
  newName: laurijuhani/broadcaster
  newTag: eac25197039e5be76428aef68fe89a5f3759c292
- name: TODO_APP
  newName: laurijuhani/todo-app
  newTag: eac25197039e5be76428aef68fe89a5f3759c292
- name: TODO_BACKEND
  newName: laurijuhani/todo-backend
  newTag: eac25197039e5be76428aef68fe89a5f3759c292
- name: TODO_JOB
  newName: laurijuhani/todo-job
  newTag: eac25197039e5be76428aef68fe89a5f3759c292
