apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ./../../base
patches:
- path: broadcaster-deployment.yaml

namePrefix: staging-

images:
- name: BROADCASTER
  newName: laurijuhani/broadcaster
  newTag: 2cd028e4383728d7ac5ccc00acec12b7d41995df
- name: TODO_APP
  newName: laurijuhani/todo-app
  newTag: 2cd028e4383728d7ac5ccc00acec12b7d41995df
- name: TODO_BACKEND
  newName: laurijuhani/todo-backend
  newTag: 2cd028e4383728d7ac5ccc00acec12b7d41995df
- name: TODO_JOB
  newName: laurijuhani/todo-job
  newTag: 2cd028e4383728d7ac5ccc00acec12b7d41995df
