apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ./../../base
patches: 
 - path: broadcaster-deployment.yaml

namePrefix: staging-

images:
  - name: TODO_APP
    newName: todo-app
    newTag: "latest"
  - name: TODO_BACKEND
    newName: todo-backend
    newTag: "latest"
  - name: TODO_JOB
    newName: todo-job
    newTag: "latest"
  - name: BROADCASTER
    newName: broadcaster
    newTag: "latest"
