apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ./../../base
patches:
- path: broadcaster-deployment.yaml

namePrefix: staging-

images:
- name: BROADCASTER
  newName: laurijuhani/broadcaster
  newTag: 1a9437ddd5e98e0586701f7b8c9af2e40deab1b5
- name: TODO_APP
  newName: laurijuhani/todo-app
  newTag: 1a9437ddd5e98e0586701f7b8c9af2e40deab1b5
- name: TODO_BACKEND
  newName: laurijuhani/todo-backend
  newTag: 1a9437ddd5e98e0586701f7b8c9af2e40deab1b5
- name: TODO_JOB
  newName: laurijuhani/todo-job
  newTag: 1a9437ddd5e98e0586701f7b8c9af2e40deab1b5
