apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pingpong-analysistemplate
  namespace: exercises
spec:
  metrics:
    - name: cpu-usage
      initialDelay: 30s
      interval: 30s
      count: 10
      successCondition: result < 200
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1750-prometheus.prometheus.svc.cluster.local:9090
          query: |
            sum(rate(container_cpu_usage_seconds_total{namespace="exercises",container!=""}[5m])) * 1000