apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ./../../base
- backup-cronjob.yaml
namePrefix: production-

images:
- name: BROADCASTER
  newName: laurijuhani/broadcaster
  newTag: 627128f52a12bfac308e6225f6e64650121cb2ef
- name: TODO_APP
  newName: laurijuhani/todo-app
  newTag: 627128f52a12bfac308e6225f6e64650121cb2ef
- name: TODO_BACKEND
  newName: laurijuhani/todo-backend
  newTag: 627128f52a12bfac308e6225f6e64650121cb2ef
- name: TODO_JOB
  newName: laurijuhani/todo-job
  newTag: 627128f52a12bfac308e6225f6e64650121cb2ef
