apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ./../../base
  - backup-cronjob.yaml
namePrefix: production-

images:
  - name: TODO_APP
    newName: todo-app
    newTag: "latest"
  - name: TODO_BACKEND
    newName: todo-backend
    newTag: "latest"
  - name: TODO_JOB
    newName: todo-job
    newTag: "latest"
  - name: BROADCASTER
    newName: broadcaster
    newTag: "latest"