apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    kind: DummySite
    plural: dummysites
    singular: dummysite
    shortNames:
      - ds
  versions:
    - name: v1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties: 
            spec:
              type: object
              properties:
                website_url:
                  type: string
      additionalPrinterColumns:
        - name: Website URL
          type: string
          jsonPath: .spec.website_url
