apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: image-claim
        - name: config-volume
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: log-output
          image: laurijuhani/log-output:3.2
          imagePullPolicy: Always
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
        - name: log-output-generator
          image: laurijuhani/log-output-generator:3.2
          imagePullPolicy: Always
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs