apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: log-output
          image: log-output:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
        - name: log-output-generator
          image: log-output-generator:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs