apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: laurijuhani/ping-pong:3.2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: ping-pong-config