apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/pv/persistentvolume.yaml
- manifests/pv/persistentvolumeclaim.yaml
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/httproute.yaml
- manifests/gateway.yaml
- manifests/pingpong-configmap.yaml
- manifests/pingpong-deployment.yaml
- manifests/pingpong-service.yaml
- manifests/postgres-service.yaml
- manifests/postgres-statefulset.yaml

images:
- name: LOG_OUTPUT
  newName: laurijuhani/log-output
  newTag: b2f92570b147755c8145b84a461f8ca6af2f2fa8
- name: LOG_OUTPUT_GENERATOR
  newName: laurijuhani/log-output-generator
  newTag: b2f92570b147755c8145b84a461f8ca6af2f2fa8
- name: PING_PONG
  newName: laurijuhani/ping-pong
  newTag: b2f92570b147755c8145b84a461f8ca6af2f2fa8
