name: Delete environment on branch delete

on: 
  delete:


env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  cleanup:
    if: github.event.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: 'Get GKE credentials'
      uses: google-github-actions/get-gke-credentials@v2
      with: 
        cluster_name: ${{ env.GKE_CLUSTER }}
        project_id: ${{ env.PROJECT_ID }}
        location: ${{ env.GKE_ZONE }}


    - name: Delete namespace
      env:
        BRANCH_REF: ${{ github.event.ref }}
      run: |
        BRANCH_NAME="${BRANCH_REF#refs/heads/}"
        kubectl delete namespace "$BRANCH_NAME" || true