name: Build and publish application

on:
  push:
    branches:
      - '**'

jobs: 
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish ping-pong
        run: |-
          cd log_output
          docker build -f Dockerfile.pingpong -t "laurijuhani/ping-pong:$GITHUB_SHA" .
          docker push "laurijuhani/ping-pong:$GITHUB_SHA"

      - name: Build and publish log-output
        run: |-
          cd log_output
          docker build -f Dockerfile -t "laurijuhani/log-output:$GITHUB_SHA" .
          docker push "laurijuhani/log-output:$GITHUB_SHA"

      - name: Build and publish log-output-generator
        run: |-
          cd log_output
          docker build -f Dockerfile.generator -t "laurijuhani/log-output-generator:$GITHUB_SHA" .
          docker push "laurijuhani/log-output-generator:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right images
        run: |-
          kustomize edit set image PING_PONG=laurijuhani/ping-pong:$GITHUB_SHA
          kustomize edit set image LOG_OUTPUT=laurijuhani/log-output:$GITHUB_SHA
          kustomize edit set image LOG_OUTPUT_GENERATOR=laurijuhani/log-output-generator:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'log_output/kustomization.yaml'
          message: New version released ${{ github.sha }}