name: Release application

on:
  push:


env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: k8s-repo
  BRANCH: ${{ github.ref_name }}

jobs: 
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      #- run: gcloud --quiet auth configure-docker
      - run: gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: 'Get GKE credentials'
        uses: google-github-actions/get-gke-credentials@v2
        with: 
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.GKE_ZONE }}


      - name: 'Form image tags'
        run: |
          echo "APP_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-app:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "BACKEND_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "JOB_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-job:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV


      - name: Build todo-app
        run: docker build -t $APP_IMAGE_TAG ./the_project/todo-app

      - name: Build todo-backend
        run: docker build -t $BACKEND_IMAGE_TAG ./the_project/todo-backend

      - name: Build todo-job
        run: docker build -t $JOB_IMAGE_TAG ./the_project/todo-job

      - name: Publish todo-app
        run: docker push $APP_IMAGE_TAG

      - name: Publish todo-backend
        run: docker push $BACKEND_IMAGE_TAG

      - name: Publish todo-job
        run: docker push $JOB_IMAGE_TAG


      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0


      - name: Deploy
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |-
          cd the_project
          kustomize edit set image TODO_APP=$APP_IMAGE_TAG
          kustomize edit set image TODO_BACKEND=$BACKEND_IMAGE_TAG
          kustomize edit set image TODO_JOB=$JOB_IMAGE_TAG
          kustomize build . | kubectl apply -f -
          kubectl get services -o wide